Using new formatting

diff --git a/Linux/tree-armv7l/functions b/Linux/tree-armv7l/functions
--- a/Linux/tree-armv7l/functions
+++ b/Linux/tree-armv7l/functions
@@ -1,30 +1,79 @@
 # -*- shell-script -*-
 
+VERBOSE=${VERBOSE:-0}
 
 ## Logging functions
 
 _log_msg() {
-    printf "${@}"
+    echo -ne "${*}" >&2
+}
+_log_file() {
+    echo "${*}" >> /initrd.log
 }
 log_success_msg() {
-    _log_msg "Success: ${@}."
+    einfo "${*}"
+    _log_file "success: ${*}"
 }
 log_failure_msg() {
-    _log_msg "Failure: ${@}."
+    eerror "${*}"
+    _log_file "failure: ${*}"
 }
 log_warning_msg() {
-    _log_msg "Warning: ${@}."
+    ewarn "${*}"
+    _log_file "warning: ${*}"
 }
 log_begin_msg() {
-    _log_msg "Begin: ${@} ... "
+    einfo "${*}..."
+    _log_file "info: ${*}"
 }
 log_end_msg() {
-    _log_msg " done.\n"
+    _log_msg ""
 }
 log_fatal_msg() {
-    _log_msg "Fatal: ${@}\n"
+    _log_msg "Fatal: ${*}\n"
+    _log_file "fatal: ${*}\n"
     sleep 5
+    # FIXME: drop a shell but reboot automatically if nothing happen on the debug shell
     reboot
+}
+einfo() {
+    _log_msg "\033[1;36m>>> \033[0m${*}\n"
+}
+esuccess() {
+    _log_msg "\033[1;32m>>> \033[0m${*}\n"
+}
+ewarn() {
+    _log_msg "\033[1;33m>>> \033[0m${*}\n"
+}
+eerror() {
+    _log_msg "\033[1;31m>>> ${*}\033[0m\n"
+}
+edebug() {
+    _log_msg "\033[0;30m>>> ${*}\033[0m\n"
+}
+die() {
+    eerror "$*"
+    rescueshell
+}
+
+run() {
+    _log_file "executing: $@"
+    edebug "Executing: $@"
+    "$@" >>/initrd.log 2>&1
+    ret=$?
+    if [[ $ret -eq 0 ]]; then
+	_log_file "Successfully ran '$@'"
+    else
+	eerror "'$@' failed"
+	return $ret
+    fi
+}
+
+rescueshell() {
+    ewarn "Rescue Shell (Busybox's /bin/sh)"
+    ewarn "To continue, press 'control-D'"
+    ewarn "To reboot, go to https://cloud.scaleway.com/"
+    exec /bin/sh
 }
 
 
@@ -39,7 +88,7 @@ signal_state() {
 
     retries=0
     while [ "${retries}" -lt "${RETRIES}" ]; do
-        has_opt nometadata || scw-update-server-state "$state"
+        has_opt nometadata || run scw-update-server-state "$state"
         if [ ${?} -eq 0 ]; then
             # log_success_msg "control plane is aware that server is ${state}"
 	    log_end_msg
@@ -111,8 +160,8 @@ get_any() {
 
 load_nolp_ko() {
     log_begin_msg "Loading nolp kernel module"
-    wget -q http://169.254.42.24/kernel/$(uname -r)/custom/nolp.ko
-    insmod $(pwd)/nolp.ko
+    run wget -q http://169.254.42.24/kernel/$(uname -r)/custom/nolp.ko
+    run insmod $(pwd)/nolp.ko
     if [ $? -eq 0 ]; then
         log_success_msg "nolp.ko successfully loaded"
         log_end_msg
@@ -125,8 +174,8 @@ load_nolp_ko() {
 
 setup_gpios() {
     # Switch booted GPIO to enable serial for user
-    echo 42 > /sys/class/gpio/export
-    echo out > /sys/class/gpio/gpio42/direction
+    run sh -c "echo 42 > /sys/class/gpio/export"
+    run sh -c "echo out > /sys/class/gpio/gpio42/direction"
 }
 
 
@@ -148,7 +197,7 @@ attach_nbd_device() {
 
 
     # Checking if device is already attached
-    $NBD_CLIENT -c /dev/nbd${device} >/dev/null 2>/dev/null
+    run $NBD_CLIENT -c /dev/nbd${device} >/dev/null 2>/dev/null
     if [ $? -eq 0 ]; then
         return
     fi
@@ -156,23 +205,23 @@ attach_nbd_device() {
     # Connecting the device
     (
 	export PATH=$(dirname $NBD_CLIENT)
-	$(basename $NBD_CLIENT) \
+	run $(basename $NBD_CLIENT) \
 	    --blocksize 4096 \
 	    --retry=$retries \
 	    $nbd_host $nbd_port \
 	    /dev/nbd${device} 2>/dev/null
     )
     local nbd_pid=$$
-    echo -1000 > /proc/$nbd_pid/oom_score_adj
+    run sh -c "echo -1000 > /proc/$nbd_pid/oom_score_adj"
 
     # Checking if device is already attached
-    $NBD_CLIENT -c /dev/nbd${device} >/dev/null 2>/dev/null || \
+    run $NBD_CLIENT -c /dev/nbd${device} >/dev/null 2>/dev/null || \
         log_fatal_msg "Device connection failed."
 
     # Fixing IO scheduler
     if grep -q '\[cfq\]' /sys/block/nbd${device}/queue/scheduler
     then
-        echo deadline > /sys/block/nbd${device}/queue/scheduler
+        run sh -c "echo deadline > /sys/block/nbd${device}/queue/scheduler"
     fi
 
     log_end_msg
@@ -185,11 +234,11 @@ mount_nbd() {
     local dest="$2"    # ie: ${rootmnt}/
 
     log_begin_msg "Mounting nbd${device} root"
-    mount /dev/nbd${device} ${dest}
+    run mount /dev/nbd${device} ${dest}
     if [ "${device}" = "0" ]; then
-	echo 0x0100 > /proc/sys/kernel/real-root-dev
+	run sh -c "echo 0x0100 > /proc/sys/kernel/real-root-dev"
     fi
-    sync
+    run sync
     log_end_msg
 }
 
@@ -212,7 +261,7 @@ attach_secondary_nbd_devices() {
 	for volume in $(oc-metadata --cached VOLUMES); do
 	    log_begin_msg "Attaching nbd${volume}"
 	    if [ "${volume}" -ne "0" ]; then
-		setup_nbd_device "${volume}"
+		run setup_nbd_device "${volume}"
 	    fi
 	    log_end_msg
 	done
